### ISSUE TITLE
ModuleNotFoundError: No module named 'click'

### ISSUE THREAD

**Issue by yllekz** [Danmou/onenote_export#9]
Hey there, I went through the run instructions, and everything went fine until I went to actually run the script. It errors out with a rather esoteric "ModuleNotFoundError: No module named 'click'" message.

```
PS C:\Users\me\Documents\GitHub\onenote_export> python onenote_export.py --select 'My Notes'
Traceback (most recent call last):
  File "onenote_export.py", line 12, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

I am doing this via Python 3.8, and tried via VS Code's terminal, PowerShell 7, Windows PowerShell 5.1, and regular cmd, to the same results.

Is it me doing something wrong?

**Comment by danmou** [comment]
Sounds like you forgot to run `pip install -r requirements.txt`
